# Generated by Django 5.1.6 on 2025-03-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='seat',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
